/* ROM-free compile-time lock on N64 struct layouts (S-tier Task 0.7,
 * FID-0035 + first half of FID-0036).
 *
 * The port reads ROM data (the StandTile navmesh, PROPDEF setup records)
 * straight into these structs, relying on the ORIGINAL N64 field offsets. That
 * layout is held together ONLY by two compiler flags applied to the game target
 * (CMakeLists.txt:707+): `-fms-extensions` (to parse bondtypes.h's `inherits`
 * anonymous-struct idiom) and `-mno-ms-bitfields` (to force SysV/Itanium
 * bit-field packing on every platform). MinGW/GCC on Windows DEFAULT to
 * -mms-bitfields, which repacks mixed bit-field structs — this is exactly what
 * crashed v0.3.2 on Windows: StandTile got repadded and the stan navmesh read
 * out of bounds.
 *
 * The `_Static_assert`s below fire at COMPILE time, so any compiler/flag drift
 * that changes an asserted size or offset fails the BUILD instead of silently
 * corrupting memory at runtime. Expected values are the current known-good
 * build's actual sizeof/offsetof (identical on macOS clang and MinGW GCC under
 * -mno-ms-bitfields — verified with tools/mingw_cross_check.sh's toolchain), so
 * they lock in the -mno-ms-bitfields layout. NOTE: the offsets differ from the
 * N64-doc offsets in bondtypes.h comments (e.g. TankRecord `rect` is documented
 * at 0x84 but sits at 0x98 here) because 64-bit PC pointers expand
 * ObjectRecord from 0x80 to 0x90 — these asserts lock the ACTUAL PC layout.
 *
 * Regenerate expected values with: tools/fidelity/gen_struct_asserts.py
 * (paste its output over the generated block below; then review the diff — a
 * changed value is either an intentional layout change or a drift finding).
 *
 * This TU must be compiled with the same GAME_DEFINES + -fms-extensions +
 * -mno-ms-bitfields as the ge007 target (see CMakeLists.txt registration). The
 * runtime body is trivial — the real check already happened at compile time. */

#include <stddef.h>
#include <stdio.h>

#include "bondtypes.h"

/* ==== BEGIN generated by tools/fidelity/gen_struct_asserts.py ==== */
/* PROPDEF record sizes — sizepropdef_pc_bytes (prop.c) and the
 * NATIVE_PORT arm of sizepropdef (loadobjectmodel.c). */
_Static_assert(sizeof(GuardRecord) == 32, "sizeof(GuardRecord) drifted from locked 32 (0x20)");
_Static_assert(sizeof(DoorRecord) == 296, "sizeof(DoorRecord) drifted from locked 296 (0x128)");
_Static_assert(sizeof(GlobalDoorScaleRecord) == 8, "sizeof(GlobalDoorScaleRecord) drifted from locked 8 (0x8)");
_Static_assert(sizeof(ObjectRecord) == 144, "sizeof(ObjectRecord) drifted from locked 144 (0x90)");
_Static_assert(sizeof(WeaponObjRecord) == 160, "sizeof(WeaponObjRecord) drifted from locked 160 (0xa0)");
_Static_assert(sizeof(KeyRecord) == 152, "sizeof(KeyRecord) drifted from locked 152 (0x98)");
_Static_assert(sizeof(TintedGlassRecord) == 168, "sizeof(TintedGlassRecord) drifted from locked 168 (0xa8)");
_Static_assert(sizeof(BodyArmourRecord) == 152, "sizeof(BodyArmourRecord) drifted from locked 152 (0x98)");
_Static_assert(sizeof(MonitorObjRecord) == 288, "sizeof(MonitorObjRecord) drifted from locked 288 (0x120)");
_Static_assert(sizeof(MultiMonitorObjRecord) == 664, "sizeof(MultiMonitorObjRecord) drifted from locked 664 (0x298)");
_Static_assert(sizeof(AutogunRecord) == 248, "sizeof(AutogunRecord) drifted from locked 248 (0xf8)");
_Static_assert(sizeof(MultiAmmoCrateRecord) == 200, "sizeof(MultiAmmoCrateRecord) drifted from locked 200 (0xc8)");
_Static_assert(sizeof(VehichleRecord) == 208, "sizeof(VehichleRecord) drifted from locked 208 (0xd0)");
_Static_assert(sizeof(AircraftRecord) == 208, "sizeof(AircraftRecord) drifted from locked 208 (0xd0)");
_Static_assert(sizeof(TankRecord) == 248, "sizeof(TankRecord) drifted from locked 248 (0xf8)");
_Static_assert(sizeof(CCTVRecord) == 272, "sizeof(CCTVRecord) drifted from locked 272 (0x110)");
_Static_assert(sizeof(AmmoCrateRecord) == 152, "sizeof(AmmoCrateRecord) drifted from locked 152 (0x98)");
_Static_assert(sizeof(SafeObjectRecord) == 40, "sizeof(SafeObjectRecord) drifted from locked 40 (0x28)");
_Static_assert(sizeof(TagObjectRecord) == 24, "sizeof(TagObjectRecord) drifted from locked 24 (0x18)");
_Static_assert(sizeof(RenameObjectRecord) == 48, "sizeof(RenameObjectRecord) drifted from locked 48 (0x30)");
_Static_assert(sizeof(LinkRecord) == 32, "sizeof(LinkRecord) drifted from locked 32 (0x20)");
_Static_assert(sizeof(SwitchRecord) == 32, "sizeof(SwitchRecord) drifted from locked 32 (0x20)");
_Static_assert(sizeof(LockDoorRecord) == 32, "sizeof(LockDoorRecord) drifted from locked 32 (0x20)");
_Static_assert(sizeof(struct setup_objective_text) == 24, "sizeof(struct setup_objective_text) drifted from locked 24 (0x18)");
_Static_assert(sizeof(struct criteria_roomentered) == 24, "sizeof(struct criteria_roomentered) drifted from locked 24 (0x18)");
_Static_assert(sizeof(struct criteria_deposit) == 24, "sizeof(struct criteria_deposit) drifted from locked 24 (0x18)");
_Static_assert(sizeof(struct criteria_picture) == 24, "sizeof(struct criteria_picture) drifted from locked 24 (0x18)");
_Static_assert(sizeof(struct objective_entry) == 16, "sizeof(struct objective_entry) drifted from locked 16 (0x10)");
_Static_assert(sizeof(StandTilePoint) == 8, "sizeof(StandTilePoint) drifted from locked 8 (0x8)");
_Static_assert(sizeof(StandTileHeaderMid) == 2, "sizeof(StandTileHeaderMid) drifted from locked 2 (0x2)");
_Static_assert(sizeof(StandTileHeaderTail) == 2, "sizeof(StandTileHeaderTail) drifted from locked 2 (0x2)");
_Static_assert(sizeof(StandTile) == 8, "sizeof(StandTile) drifted from locked 8 (0x8)");
_Static_assert(sizeof(StandFilePoint) == 8, "sizeof(StandFilePoint) drifted from locked 8 (0x8)");
_Static_assert(sizeof(StandFileTile) == 8, "sizeof(StandFileTile) drifted from locked 8 (0x8)");

/* Union / bitfield-adjacent field offsets (FID-0036) + StandTile navmesh family. */
_Static_assert(offsetof(KeyRecord, keyID) == 144, "offsetof(KeyRecord, keyID) drifted from locked 144 (0x90)");
_Static_assert(offsetof(MultiAmmoCrateRecord, unk80) == 144, "offsetof(MultiAmmoCrateRecord, unk80) drifted from locked 144 (0x90)");
_Static_assert(offsetof(MultiAmmoCrateRecord, slots) == 144, "offsetof(MultiAmmoCrateRecord, slots) drifted from locked 144 (0x90)");
_Static_assert(offsetof(TankRecord, rect) == 152, "offsetof(TankRecord, rect) drifted from locked 152 (0x98)");
_Static_assert(offsetof(StandTile, room) == 3, "offsetof(StandTile, room) drifted from locked 3 (0x3)");
_Static_assert(offsetof(StandTile, mid) == 4, "offsetof(StandTile, mid) drifted from locked 4 (0x4)");
_Static_assert(offsetof(StandTile, tail) == 6, "offsetof(StandTile, tail) drifted from locked 6 (0x6)");
_Static_assert(offsetof(StandTile, points) == 8, "offsetof(StandTile, points) drifted from locked 8 (0x8)");
_Static_assert(offsetof(StandFileTile, room) == 3, "offsetof(StandFileTile, room) drifted from locked 3 (0x3)");
_Static_assert(offsetof(StandFileTile, mid) == 4, "offsetof(StandFileTile, mid) drifted from locked 4 (0x4)");
_Static_assert(offsetof(StandFileTile, tail) == 6, "offsetof(StandFileTile, tail) drifted from locked 6 (0x6)");
/* ==== END generated ==== */

int main(void) {
    /* If this TU compiled at all, every _Static_assert above held. The runtime
     * body exists only so the ctest has something to link and run. */
    printf("test_struct_layout: PASS (45 layout asserts held at compile time)\n");
    return 0;
}
