/* ROM-free compile-time lock on N64 struct layouts (S-tier Task 0.7,
 * FID-0035 + first half of FID-0036).
 *
 * The port reads ROM data (the StandTile navmesh, PROPDEF setup records)
 * straight into these structs, relying on the ORIGINAL N64 field offsets. That
 * layout is held together ONLY by two compiler flags applied to the game target
 * (CMakeLists.txt:707+): `-fms-extensions` (to parse bondtypes.h's `inherits`
 * anonymous-struct idiom) and `-mno-ms-bitfields` (to force SysV/Itanium
 * bit-field packing on every platform). MinGW/GCC on Windows DEFAULT to
 * -mms-bitfields, which repacks mixed bit-field structs — this is exactly what
 * crashed v0.3.2 on Windows: StandTile got repadded and the stan navmesh read
 * out of bounds.
 *
 * The `_Static_assert`s below fire at COMPILE time, so any compiler/flag drift
 * that changes an asserted size or offset fails the BUILD instead of silently
 * corrupting memory at runtime. Expected values are the current known-good
 * build's actual sizeof/offsetof (identical on macOS clang and MinGW GCC under
 * -mno-ms-bitfields — verified with tools/mingw_cross_check.sh's toolchain), so
 * they lock in the -mno-ms-bitfields layout. NOTE: the offsets differ from the
 * N64-doc offsets in bondtypes.h comments (e.g. TankRecord `rect` is documented
 * at 0x84 but sits at 0x98 here) because 64-bit PC pointers expand
 * ObjectRecord from 0x80 to 0x90 — these asserts lock the ACTUAL PC layout.
 *
 * Regenerate expected values with: tools/fidelity/gen_struct_asserts.py
 * (paste its output over the generated block below; then review the diff — a
 * changed value is either an intentional layout change or a drift finding).
 *
 * This TU must be compiled with the same GAME_DEFINES + -fms-extensions +
 * -mno-ms-bitfields as the ge007 target (see CMakeLists.txt registration). The
 * runtime body is trivial — the real check already happened at compile time. */

#include <stddef.h>
#include <stdio.h>

#include "bondtypes.h"
#include "bondview.h"   /* struct hand / struct player — FID-0085 hand-matrix lock */

/* ==== BEGIN generated by tools/fidelity/gen_struct_asserts.py ==== */
/* PROPDEF record sizes — sizepropdef_pc_bytes (prop.c) and the
 * NATIVE_PORT arm of sizepropdef (loadobjectmodel.c). */
_Static_assert(sizeof(GuardRecord) == 32, "sizeof(GuardRecord) drifted from locked 32 (0x20)");
_Static_assert(sizeof(DoorRecord) == 296, "sizeof(DoorRecord) drifted from locked 296 (0x128)");
_Static_assert(sizeof(GlobalDoorScaleRecord) == 8, "sizeof(GlobalDoorScaleRecord) drifted from locked 8 (0x8)");
_Static_assert(sizeof(ObjectRecord) == 144, "sizeof(ObjectRecord) drifted from locked 144 (0x90)");
_Static_assert(sizeof(WeaponObjRecord) == 160, "sizeof(WeaponObjRecord) drifted from locked 160 (0xa0)");
_Static_assert(sizeof(KeyRecord) == 152, "sizeof(KeyRecord) drifted from locked 152 (0x98)");
_Static_assert(sizeof(TintedGlassRecord) == 168, "sizeof(TintedGlassRecord) drifted from locked 168 (0xa8)");
_Static_assert(sizeof(BodyArmourRecord) == 152, "sizeof(BodyArmourRecord) drifted from locked 152 (0x98)");
_Static_assert(sizeof(MonitorObjRecord) == 288, "sizeof(MonitorObjRecord) drifted from locked 288 (0x120)");
_Static_assert(sizeof(MultiMonitorObjRecord) == 664, "sizeof(MultiMonitorObjRecord) drifted from locked 664 (0x298)");
_Static_assert(sizeof(AutogunRecord) == 248, "sizeof(AutogunRecord) drifted from locked 248 (0xf8)");
_Static_assert(sizeof(MultiAmmoCrateRecord) == 200, "sizeof(MultiAmmoCrateRecord) drifted from locked 200 (0xc8)");
_Static_assert(sizeof(VehichleRecord) == 208, "sizeof(VehichleRecord) drifted from locked 208 (0xd0)");
_Static_assert(sizeof(AircraftRecord) == 208, "sizeof(AircraftRecord) drifted from locked 208 (0xd0)");
_Static_assert(sizeof(TankRecord) == 248, "sizeof(TankRecord) drifted from locked 248 (0xf8)");
_Static_assert(sizeof(CCTVRecord) == 272, "sizeof(CCTVRecord) drifted from locked 272 (0x110)");
_Static_assert(sizeof(AmmoCrateRecord) == 152, "sizeof(AmmoCrateRecord) drifted from locked 152 (0x98)");
_Static_assert(sizeof(SafeObjectRecord) == 40, "sizeof(SafeObjectRecord) drifted from locked 40 (0x28)");
_Static_assert(sizeof(TagObjectRecord) == 24, "sizeof(TagObjectRecord) drifted from locked 24 (0x18)");
_Static_assert(sizeof(RenameObjectRecord) == 48, "sizeof(RenameObjectRecord) drifted from locked 48 (0x30)");
_Static_assert(sizeof(LinkRecord) == 32, "sizeof(LinkRecord) drifted from locked 32 (0x20)");
_Static_assert(sizeof(SwitchRecord) == 32, "sizeof(SwitchRecord) drifted from locked 32 (0x20)");
_Static_assert(sizeof(LockDoorRecord) == 32, "sizeof(LockDoorRecord) drifted from locked 32 (0x20)");
_Static_assert(sizeof(struct setup_objective_text) == 24, "sizeof(struct setup_objective_text) drifted from locked 24 (0x18)");
_Static_assert(sizeof(struct criteria_roomentered) == 24, "sizeof(struct criteria_roomentered) drifted from locked 24 (0x18)");
_Static_assert(sizeof(struct criteria_deposit) == 24, "sizeof(struct criteria_deposit) drifted from locked 24 (0x18)");
_Static_assert(sizeof(struct criteria_picture) == 24, "sizeof(struct criteria_picture) drifted from locked 24 (0x18)");
_Static_assert(sizeof(struct objective_entry) == 16, "sizeof(struct objective_entry) drifted from locked 16 (0x10)");
_Static_assert(sizeof(StandTilePoint) == 8, "sizeof(StandTilePoint) drifted from locked 8 (0x8)");
_Static_assert(sizeof(StandTileHeaderMid) == 2, "sizeof(StandTileHeaderMid) drifted from locked 2 (0x2)");
_Static_assert(sizeof(StandTileHeaderTail) == 2, "sizeof(StandTileHeaderTail) drifted from locked 2 (0x2)");
_Static_assert(sizeof(StandTile) == 8, "sizeof(StandTile) drifted from locked 8 (0x8)");
_Static_assert(sizeof(StandFilePoint) == 8, "sizeof(StandFilePoint) drifted from locked 8 (0x8)");
_Static_assert(sizeof(StandFileTile) == 8, "sizeof(StandFileTile) drifted from locked 8 (0x8)");

/* Union / bitfield-adjacent field offsets (FID-0036) + StandTile navmesh family. */
_Static_assert(offsetof(KeyRecord, keyID) == 144, "offsetof(KeyRecord, keyID) drifted from locked 144 (0x90)");
_Static_assert(offsetof(MultiAmmoCrateRecord, unk80) == 144, "offsetof(MultiAmmoCrateRecord, unk80) drifted from locked 144 (0x90)");
_Static_assert(offsetof(MultiAmmoCrateRecord, slots) == 144, "offsetof(MultiAmmoCrateRecord, slots) drifted from locked 144 (0x90)");
_Static_assert(offsetof(TankRecord, rect) == 152, "offsetof(TankRecord, rect) drifted from locked 152 (0x98)");
_Static_assert(offsetof(StandTile, room) == 3, "offsetof(StandTile, room) drifted from locked 3 (0x3)");
_Static_assert(offsetof(StandTile, mid) == 4, "offsetof(StandTile, mid) drifted from locked 4 (0x4)");
_Static_assert(offsetof(StandTile, tail) == 6, "offsetof(StandTile, tail) drifted from locked 6 (0x6)");
_Static_assert(offsetof(StandTile, points) == 8, "offsetof(StandTile, points) drifted from locked 8 (0x8)");
_Static_assert(offsetof(StandFileTile, room) == 3, "offsetof(StandFileTile, room) drifted from locked 3 (0x3)");
_Static_assert(offsetof(StandFileTile, mid) == 4, "offsetof(StandFileTile, mid) drifted from locked 4 (0x4)");
_Static_assert(offsetof(StandFileTile, tail) == 6, "offsetof(StandFileTile, tail) drifted from locked 6 (0x6)");
/* ==== END generated ==== */

/* ---- FID-0085: grenade-round projectile-init-matrix hand field (manual) ----
 * sub_GAME_7F05F73C (grenade launcher / flare pistol / piton gun round spawn)
 * copies the projectile init matrix from &hands[hand].throw_item_pos_related.
 * Retail US ASM reads it as the raw N64 byte offset g_CurrentPlayer + hand*936
 * + 0xAD8, i.e. hands@0x870 + field@+0x268. On the 64-bit port layout, pointer
 * fields inside struct hand (audioHandle, rocket, ...) before that field expand
 * 4->8B, so the field is NOT at N64 0x268 and the hand stride is NOT 936. The
 * native gun.c body (post-fix) MUST reach it by C field access, never the raw
 * offset. These asserts lock the actual PC layout and, critically, prove the
 * raw N64 offset the legacy (GE007_NO_PROJECTILE_INIT_MTX_FIX) path uses does
 * NOT coincide with the real field — so the default-ON fix is load-bearing.
 * Regenerate expected values with tools/fidelity/gen_struct_asserts.py if the
 * layout intentionally changes; a drift here is a fix-invalidating finding. */
#define FID0085_N64_HAND_STRIDE   936     /* ASM *936 strength-reduce            */
#define FID0085_N64_HANDS_BASE    0x870   /* addiu $t9,$t8,0x870                 */
#define FID0085_N64_MTX_FIELD     0x268   /* 0xAD8 - 0x870 (raw path within-hand)*/
_Static_assert(sizeof(struct hand) == 968,
    "sizeof(struct hand) drifted from locked 968 (0x3c8) — FID-0085 stride lock");
_Static_assert(offsetof(struct hand, throw_item_pos_related) == 0x274,
    "offsetof(struct hand, throw_item_pos_related) drifted from locked 0x274 — FID-0085");
_Static_assert(offsetof(struct hand, throw_item_pos_related) != FID0085_N64_MTX_FIELD,
    "native throw_item_pos_related coincides with the raw N64 0x268 offset — "
    "the legacy raw+0xAD8 read would be correct and the FID-0085 fix moot; re-derive");
_Static_assert(sizeof(struct hand) != FID0085_N64_HAND_STRIDE,
    "native hand stride equals the N64 936 — per-hand raw stride would be correct; re-derive");

/* ---- FID-0087: grenade-round projectile SPAWN POSITION hand field ----
 * sub_GAME_7F05F73C passes the spawn position as retail hand+0x2E8 = field_B58.
 * On the 64-bit layout pointer fields inside struct hand before field_B58 expand
 * 4->8B (+0xC), so it sits at native 0x2F4 not 0x2E8; the legacy raw read
 * (GE007_NO_GRENADE_SPAWN_POS_FIX) would land on field_B4C/B50/B54. */
#define FID0087_N64_POS_FIELD  0x2E8   /* raw (u8*)hand + 0x2E8 legacy read */
_Static_assert(offsetof(struct hand, field_B58) == 0x2F4,
    "offsetof(struct hand, field_B58) drifted from locked 0x2F4 — FID-0087");
_Static_assert(offsetof(struct hand, field_B58) != FID0087_N64_POS_FIELD,
    "native field_B58 coincides with the raw N64 hand+0x2E8 offset — the legacy "
    "raw read would be correct and the FID-0087 fix moot; re-derive");

/* ---- FID-0088 / FID-0092 / FID-0093: post-hands PLAYER fields read/written via
 * raw N64 byte offsets in the legacy paths. The hands[] array grows on the
 * 64-bit layout (per-hand 936->968 + pre-hands pointer growth), shifting every
 * field after hands[] by a single uniform delta, so NONE of these fields sit at
 * their raw N64 offset. A `==` here would mean the raw read/write coincides with
 * the real field and the default-ON fix is moot -> a fix-invalidating drift. */
#define FID0088_N64_TILECOLOR      0xFDC   /* raw (u8*)g_CurrentPlayer + 0xFDC  */
#define FID0091_N64_LASTZTRIGGER   0x105C  /* raw (u8*)g_CurrentPlayer + 0x105C */
#define FID0092_N64_GUNAMMOOFF     0x1064  /* raw (u8*)g_CurrentPlayer + 0x1064 */
_Static_assert(offsetof(struct player, tileColor) != FID0088_N64_TILECOLOR,
    "native player.tileColor coincides with raw N64 0xFDC — FID-0088 fix moot; re-derive");
_Static_assert(offsetof(struct player, last_z_trigger_timer) != FID0091_N64_LASTZTRIGGER,
    "native player.last_z_trigger_timer coincides with raw N64 0x105C — FID-0092 fix moot");
_Static_assert(offsetof(struct player, gunammooff) != FID0092_N64_GUNAMMOOFF,
    "native player.gunammooff coincides with raw N64 0x1064 — FID-0093 fix moot");
/* The post-hands shift is a single uniform delta (one hands[] growth event): */
_Static_assert(offsetof(struct player, last_z_trigger_timer) - FID0091_N64_LASTZTRIGGER
            == offsetof(struct player, tileColor) - FID0088_N64_TILECOLOR,
    "post-hands native shift not uniform (tileColor vs last_z_trigger_timer)");
_Static_assert(offsetof(struct player, gunammooff) - FID0092_N64_GUNAMMOOFF
            == offsetof(struct player, tileColor) - FID0088_N64_TILECOLOR,
    "post-hands native shift not uniform (tileColor vs gunammooff)");

int main(void) {
    /* If this TU compiled at all, every _Static_assert above held. The runtime
     * body exists only so the ctest has something to link and run. */
    printf("test_struct_layout: PASS (45 layout asserts + FID-0085 hand-matrix "
           "lock + FID-0087/0088/0091/0092 raw-cast field locks held at compile "
           "time)\n");
    return 0;
}
