"""FID-0063 regression lane -- pins the PRNG stepper and the per-tick
randomGetNext() call-count extraction of ``tools/fidelity/rng_callcount_diff.py``.

The stepper must be bit-exact to ``src/random.c randomGetNext`` (the NONMATCHING
body, which is the live native path and is bit-faithful to the retail
``GLOBAL_ASM``). Golden vectors below were generated by compiling the exact C
body (u64 shift semantics) and stepping three seeds:

  * ``0xAB8D9F7781280783`` -- the g_randomSeed compile-time boot constant,
  * ``0x0000000012345679`` -- the deterministic-tape seed (0x12345678) after
    ``randomSetSeed``'s ``+1``,
  * ``0x0000000000000001`` -- a minimal seed.

A live-capture cross-check also exists at runtime: the extractor validates its
chain walk against the native emitter's exact ``rng.call_count`` on every run
(``validation.native_counter_vs_chainwalk``).

All fixtures are synthetic -- nothing here is ROM-derived.

Run: python3 -m unittest tools.tests.test_rng_callcount_diff
"""
from __future__ import annotations

import sys
import unittest
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

from tools.fidelity import rng_callcount_diff as rcd  # noqa: E402

# (initial_seed, [post-step state after step 1..10])
GOLDEN = [
    (
        0xAB8D9F7781280783,
        [
            0x0000000140EC37CF,
            0x00000001630AEDD7,
            0x000000011F58071E,
            0x000000000FDDE372,
            0x00000000D9D9DC24,
            0x00000000F12EA100,
            0x00000000928759A8,
            0x000000003CD92F19,
            0x000000018C9D0F45,
            0x0000000116BAD6C9,
        ],
    ),
    (
        0x0000000012345679,
        [
            0x000000014C7DBFFB,
            0x000000017DC16821,
            0x00000001A862AE96,
            0x00000000FED838A6,
            0x00000000FCE6739D,
            0x00000001194AE85A,
            0x000000002220D60F,
            0x000000011C709AC0,
            0x0000000087944519,
            0x00000001079BB2F5,
        ],
    ),
    (
        0x0000000000000001,
        [
            0x0000000100001000,
            0x0000000081000010,
            0x0000000040810400,
            0x0000000030008100,
            0x0000000010104181,
            0x000000010C103001,
            0x0000000185080050,
            0x0000000042810400,
            0x0000000031008110,
            0x0000000010914181,
        ],
    ),
]


class TestPrngStepper(unittest.TestCase):
    def test_golden_sequences(self) -> None:
        for init, states in GOLDEN:
            s = init
            for i, expect in enumerate(states):
                s = rcd.prng_step(s)
                self.assertEqual(
                    s, expect,
                    f"seed 0x{init:016X} step {i + 1}: "
                    f"got 0x{s:016X}, want 0x{expect:016X}",
                )

    def test_state_collapses_to_33_bits(self) -> None:
        # After one step the state is < 2^33 for ANY 64-bit input -- this is
        # what makes seed-based call-count recovery tractable.
        for init in (0xFFFFFFFFFFFFFFFF, 0xAB8D9F7781280783, 0xDEADBEEF12345678):
            self.assertLess(rcd.prng_step(init), 1 << 33)

    def test_return_value_is_low_word(self) -> None:
        s = rcd.prng_step(0xAB8D9F7781280783)
        self.assertEqual(rcd.prng_value(s), 0x40EC37CF)

    def test_steps_between(self) -> None:
        init, states = GOLDEN[0]
        self.assertEqual(rcd.steps_between(init, init, 10), 0)
        for k, state in enumerate(states, start=1):
            self.assertEqual(rcd.steps_between(init, state, 100), k)
        # unreachable within bound -> None
        self.assertIsNone(rcd.steps_between(init, 0x123456789, 5))


def _record(f: int, g: int, seed: int, call_count: int | None = None,
            speed: float = 0.0) -> dict:
    rng: dict = {"seed": f"0x{seed:016X}", "seed_low": seed & 0xFFFFFFFF}
    if call_count is not None:
        rng["call_count"] = call_count
    return {
        "f": f,
        "move": {"global": g, "speed": [speed, 0.0], "raw": [speed, 0.0]},
        "rng": rng,
    }


def _chain(seed: int, n: int) -> list[int]:
    out = []
    s = seed
    for _ in range(n):
        s = rcd.prng_step(s)
        out.append(s)
    return out


class TestRelTickSampling(unittest.TestCase):
    def test_last_record_per_tick_wins(self) -> None:
        seeds = _chain(1, 10)
        recs = [
            _record(1, 100, seeds[0]),
            _record(2, 100, seeds[3]),  # later sample same tick: wins
            _record(3, 101, seeds[7]),
        ]
        samples = rcd.rel_tick_samples(recs, 0, 100)
        self.assertEqual([s["rel_tick"] for s in samples], [0, 1])
        self.assertEqual(samples[0]["seed"], seeds[3])

    def test_segment_gate_stops_at_global_reset(self) -> None:
        # A mission restart resets g_GlobalTimer; records after the reset
        # re-visit the same rel ticks with unrelated state and must NOT
        # overwrite the onset segment (the dam_combat_guard6 stock capture
        # contains exactly this: Bond dies, the game resets at f=4802).
        seeds = _chain(1, 10)
        recs = [
            _record(1, 100, seeds[0]),
            _record(2, 103, seeds[1]),
            _record(3, 0, seeds[8]),    # reset: segment boundary
            _record(4, 103, seeds[9]),  # would overwrite rel 3 if not gated
        ]
        samples = rcd.rel_tick_samples(recs, 0, 100)
        self.assertEqual([s["rel_tick"] for s in samples], [0, 3])
        self.assertEqual(samples[1]["seed"], seeds[1])


class TestChainWalk(unittest.TestCase):
    def test_cumulative_counts(self) -> None:
        seeds = _chain(0xAB8D9F7781280783, 30)
        # ticks 0,3,6 sampled after 0, 7 and 30 total draws
        samples = [
            {"rel_tick": 0, "seed": seeds[0], "call_count": None, "f": 1, "global": 0},
            {"rel_tick": 3, "seed": seeds[7], "call_count": None, "f": 2, "global": 3},
            {"rel_tick": 6, "seed": seeds[29], "call_count": None, "f": 3, "global": 6},
        ]
        walk = rcd.chain_walk(samples, max_steps=100)
        self.assertEqual(walk["cum"], {0: 0, 3: 7, 6: 29})
        self.assertEqual(walk["discontinuities"], [])

    def test_reseed_reported_as_discontinuity(self) -> None:
        seeds = _chain(0xAB8D9F7781280783, 5)
        samples = [
            {"rel_tick": 0, "seed": seeds[0], "call_count": None, "f": 1, "global": 0},
            {"rel_tick": 3, "seed": 0x1FFFFFFFF, "call_count": None, "f": 2, "global": 3},
        ]
        walk = rcd.chain_walk(samples, max_steps=50)
        self.assertEqual(len(walk["discontinuities"]), 1)
        self.assertEqual(walk["discontinuities"][0]["rel_tick"], 3)

    def test_per_span_series_uses_common_grid(self) -> None:
        cums = {0: 0, 1: 5, 2: 9, 3: 15, 6: 30}
        # spans over the COMMON tick grid (0,3,6), not the native sampling grid
        self.assertEqual(
            rcd.per_span_series(cums, [0, 3, 6]), {3: 15, 6: 15}
        )


if __name__ == "__main__":
    unittest.main()
