#!/usr/bin/env python3
"""Generate a complete reference of GE007_* environment flags from the source.

The port gates behavior on GE007_* environment variables. This scans the tracked
C/C++ source for every flag reference — raw getenv("GE007_..."), the ge_env_bool
helper, and the registering port_env_bool/int/float accessors — and emits a
Markdown catalog so the full flag surface is documented (and can be diffed in CI
against the docs, so it can't silently drift).

Usage:
  tools/gen_env_reference.py [--repo-root DIR] [--out FILE] [--check FILE]

  (no --out)     print the catalog to stdout
  --out FILE     write the catalog to FILE
  --check FILE   regenerate and compare to FILE; exit 1 if they differ (CI gate)
"""
from __future__ import annotations

import argparse
import os
import re
import subprocess
import sys

# port_env_bool("GE007_X", default, "help")  /  ge_env_bool("GE007_X", default)
REG_RE = re.compile(
    r'\b(port_env_bool|port_env_int|port_env_float|ge_env_bool)\s*\(\s*'
    r'"(GE007_[A-Z0-9_]+)"\s*,\s*([^,]+?)\s*(?:,\s*("(?:[^"\\]|\\.)*"|NULL))?\s*\)'
)
# raw getenv("GE007_X")
GETENV_RE = re.compile(r'\bgetenv\s*\(\s*"(GE007_[A-Z0-9_]+)"\s*\)')

KIND = {
    "port_env_bool": "bool",
    "port_env_int": "int",
    "port_env_float": "float",
    "ge_env_bool": "bool",
}


def repo_root(explicit: str | None) -> str:
    if explicit:
        return os.path.abspath(explicit)
    try:
        out = subprocess.check_output(
            ["git", "rev-parse", "--show-toplevel"], text=True, stderr=subprocess.DEVNULL
        )
        return out.strip()
    except (OSError, subprocess.CalledProcessError):
        return os.getcwd()


def source_files(root: str) -> list[str]:
    out = subprocess.check_output(
        ["git", "ls-files", "src/*.c", "src/*.h", "src/**/*.c", "src/**/*.h",
         "src/**/*.cpp", "src/**/*.mm", "include/**/*.h"],
        cwd=root, text=True,
    )
    return [l for l in out.splitlines() if l]


def build_catalog(root: str) -> dict[str, dict]:
    flags: dict[str, dict] = {}

    def ensure(name: str) -> dict:
        return flags.setdefault(
            name, {"name": name, "kind": "?", "default": "", "help": "", "refs": 0}
        )

    for rel in source_files(root):
        try:
            text = open(os.path.join(root, rel), encoding="utf-8", errors="replace").read()
        except OSError:
            continue
        for m in REG_RE.finditer(text):
            fn, name, default, help_lit = m.group(1), m.group(2), m.group(3), m.group(4)
            e = ensure(name)
            e["kind"] = KIND.get(fn, e["kind"])
            if e["default"] == "":
                e["default"] = default.strip()
            if help_lit and help_lit != "NULL" and not e["help"]:
                e["help"] = help_lit[1:-1]
            e["refs"] += 1
        for m in GETENV_RE.finditer(text):
            ensure(m.group(1))["refs"] += 1

    return flags


def render(flags: dict[str, dict]) -> str:
    lines = [
        "# GE007_* environment flag reference",
        "",
        "_Generated by `tools/gen_env_reference.py` — do not edit by hand._",
        "",
        "The port gates diagnostic and opt-in behavior on `GE007_*` environment",
        "variables. This is the complete flag surface scanned from the source.",
        "Flags read through the registering `port_env_*` accessors (or `ge_env_bool`)",
        "carry a type, default, and description here; flags still read through a raw",
        "`getenv` show none of those — migrating them to `port_env_*` fills them in.",
        "",
        f"**{len(flags)} flags** found across the source.",
        "",
        "| Flag | Type | Default | Refs | Description |",
        "| --- | --- | --- | --- | --- |",
    ]
    for name in sorted(flags):
        e = flags[name]
        default = e["default"].replace("|", "\\|") if e["default"] else ""
        help_ = e["help"].replace("|", "\\|") if e["help"] else ""
        lines.append(f"| `{name}` | {e['kind']} | {default} | {e['refs']} | {help_} |")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--repo-root", default=None)
    ap.add_argument("--out", default=None)
    ap.add_argument("--check", default=None)
    args = ap.parse_args()

    root = repo_root(args.repo_root)
    catalog = render(build_catalog(root))

    if args.check:
        try:
            existing = open(os.path.join(root, args.check), encoding="utf-8").read()
        except OSError:
            print(f"FAIL: {args.check} does not exist; run gen_env_reference.py --out {args.check}", file=sys.stderr)
            return 1
        if existing != catalog:
            print(f"FAIL: {args.check} is stale; regenerate with tools/gen_env_reference.py --out {args.check}", file=sys.stderr)
            return 1
        print(f"PASS: {args.check} matches the source flag surface.")
        return 0

    if args.out:
        with open(os.path.join(root, args.out), "w", encoding="utf-8") as fh:
            fh.write(catalog)
        print(f"wrote {args.out}")
    else:
        sys.stdout.write(catalog)
    return 0


if __name__ == "__main__":
    sys.exit(main())
