#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

ROUTE_JSON="$ROOT_DIR/tools/rom_oracle_routes/dam_regular_glass_shatter_pad10092_impact_visual_probe.json"
TEXGEN_DIR="/tmp/mgb64_glass_pad10092_texgen_roi_material_probe"
ROI_SEMANTICS_JSON="/tmp/mgb64_glass_pad10092_roi_pixel_semantics_current/pad10092_roi_pixel_semantics.json"
OUT_DIR=""
FRAME="latest"
REGIONS=()

usage() {
    cat <<USAGE
Usage: $0 [--texgen-dir DIR] [--roi-pixel-semantics FILE] [--out-dir DIR]
          [--route-json FILE] [--frame latest|all|N] [--region NAME]

Read-only Dam pad-10092 trace-to-pixel correlation probe. It consumes the
TEXGEN-MATERIAL log and ROI pixel semantics artifacts generated by the previous
pad-10092 probes; it does not launch the game.
USAGE
}

while [[ $# -gt 0 ]]; do
    case "$1" in
        --texgen-dir)
            TEXGEN_DIR="$2"
            shift 2
            ;;
        --roi-pixel-semantics)
            ROI_SEMANTICS_JSON="$2"
            shift 2
            ;;
        --out-dir)
            OUT_DIR="$2"
            shift 2
            ;;
        --route-json)
            ROUTE_JSON="$2"
            shift 2
            ;;
        --frame)
            FRAME="$2"
            shift 2
            ;;
        --region)
            REGIONS+=("--region" "$2")
            shift 2
            ;;
        -h|--help)
            usage
            exit 0
            ;;
        *)
            echo "unknown argument: $1" >&2
            usage >&2
            exit 2
            ;;
    esac
done

if [[ -z "$OUT_DIR" ]]; then
    OUT_DIR="$(mktemp -d /tmp/mgb64_glass_pad10092_texgen_roi_pixel_correlation.XXXXXX)"
fi

LOG="$TEXGEN_DIR/default/native_dam_regular_glass_shatter_pad10092_impact_visual_probe.log"
AUDIT="$TEXGEN_DIR/glass_pad10092_texgen_roi_material_audit.json"

mkdir -p "$OUT_DIR"

python3 "$ROOT_DIR/tools/correlate_texgen_roi_pixel_semantics.py" "$LOG" \
    --route-json "$ROUTE_JSON" \
    --roi-pixel-semantics "$ROI_SEMANTICS_JSON" \
    --texgen-audit "$AUDIT" \
    --frame "$FRAME" \
    "${REGIONS[@]}" \
    --json-out "$OUT_DIR/pad10092_texgen_roi_pixel_correlation.json" \
    > "$OUT_DIR/pad10092_texgen_roi_pixel_correlation.txt"

echo "[TEXGEN-ROI-PIXEL] wrote $OUT_DIR/pad10092_texgen_roi_pixel_correlation.json"
